enum ACTIONS {
  DO_GET_POKEMONS = "DO_GET_POKEMONS",
  DO_GET_POKEMON = "DO_GET_POKEMON",
  DO_CLEAN_POKEMONS = "DO_CLEAN_POKEMONS",
  DO_SAVE_AS_FAVORITE = "DO_SAVE_AS_FAVORITE",
  DO_GET_FAVORITE_POKEMONS = "DO_GET_FAVORITE_POKEMONS",
  DO_GET_SELECTED_POKEMON = "DO_GET_SELECTED_POKEMON",
}

export { ACTIONS };
